import { YgoCard } from '../types/ygo';

// 本地常用卡库 Mock
export const MOCK_LOCAL_CARDS: YgoCard[] = [
  {
    id: 18144506,
    name: "神鹰羽毛吹雪",
    jpName: "ハーピィの羽根吹雪",
    enName: "Harpie's Feather Storm",
    type: "trap",
    subType: "【通常陷阱】",
    desc: "自己场上有风属性鸟兽族怪兽存在的场合，这张卡的发动也可以从手卡进行。①：自己场上有鸟兽族怪兽存在的场合才能发动。直到回合结束时，对方发动的怪兽的效果无效化。",
    imageUrl: "https://cdn.233.momobako.com/ygopro/pics/18144506.jpg",
    source: "LOCAL_DB",
    rarity: "UR",
    banlistInfo: { masterDuel: 'Forbidden', ocg: 'Forbidden', tcg: 'Unlimited' }
  },
  {
    id: 44405066,
    name: "烙印融合",
    jpName: "烙印融合",
    enName: "Branded Fusion",
    type: "spell",
    subType: "【通常魔法】",
    desc: "这个卡名的卡在1回合只能发动1张，发动这张卡的回合，自己不能从额外卡组把融合怪兽以外的怪兽特殊召唤。①：从自己的手卡·卡组·场上把融合怪兽决定的2只融合素材怪兽送去墓地，把包含「阿不思的落胤」的那1只融合怪兽从额外卡组融合召唤。",
    imageUrl: "https://cdn.233.momobako.com/ygopro/pics/44405066.jpg",
    source: "LOCAL_DB",
    rarity: "UR",
    banlistInfo: { masterDuel: 'Limited', ocg: 'Limited', tcg: 'Unlimited' }
  },
  {
    id: 37744402,
    name: "灰流丽",
    jpName: "灰流うらら",
    enName: "Ash Blossom & Joyous Spring",
    type: "monster",
    subType: "【效果怪兽/调整】",
    attribute: "FIRE",
    race: "不死族",
    level: 3,
    atk: 0,
    def: 1800,
    desc: "这个卡名的效果1回合只能使用1次。①：包含以下任意效果的魔法·陷阱·怪兽的效果发动时，把这张卡从手卡丢弃才能发动。那个效果无效。",
    imageUrl: "https://cdn.233.momobako.com/ygopro/pics/37744402.jpg",
    source: "LOCAL_DB",
    rarity: "UR",
    banlistInfo: { masterDuel: 'Unlimited', ocg: 'Unlimited', tcg: 'Unlimited' }
  },
  {
    id: 23434538,
    name: "增殖的G",
    jpName: "増殖するG",
    enName: "Maxx \"C\"",
    type: "monster",
    subType: "【效果怪兽】",
    attribute: "EARTH",
    race: "昆虫族",
    level: 2,
    atk: 500,
    def: 200,
    desc: "这个卡名的效果1回合只能使用1次，在双方回合也能发动。①：把这张卡从手卡送去墓地才能发动。这个回合中，每次对方对怪兽的特殊召唤成功，自己必须从卡组抽1张。",
    imageUrl: "https://cdn.233.momobako.com/ygopro/pics/23434538.jpg",
    source: "LOCAL_DB",
    rarity: "UR",
    banlistInfo: { masterDuel: 'Semi-Limited', ocg: 'Semi-Limited', tcg: 'Forbidden' }
  },
  {
    id: 10045474,
    name: "无限泡影",
    jpName: "無限泡影",
    enName: "Infinite Impermanence",
    type: "trap",
    subType: "【通常陷阱】",
    desc: "自己场上没有卡存在的场合，这张卡的发动也可以从手卡进行。①：以对方场上1只表侧表示怪兽为对象才能发动。那只怪兽的效果直到回合结束时无效。",
    imageUrl: "https://cdn.233.momobako.com/ygopro/pics/10045474.jpg",
    source: "LOCAL_DB",
    rarity: "UR",
    banlistInfo: { masterDuel: 'Unlimited', ocg: 'Unlimited', tcg: 'Unlimited' }
  },
  {
    id: 55144522,
    name: "强欲之壶",
    jpName: "強欲な壺",
    enName: "Pot of Greed",
    type: "spell",
    subType: "【通常魔法】",
    desc: "①：自己从卡组抽2张。",
    imageUrl: "https://cdn.233.momobako.com/ygopro/pics/55144522.jpg",
    source: "LOCAL_DB",
    rarity: "UR",
    banlistInfo: { masterDuel: 'Forbidden', ocg: 'Forbidden', tcg: 'Forbidden' }
  },
  {
    id: 29301450,
    name: "S:P小夜",
    jpName: "Ｓ：Ｐリトルナイト",
    enName: "S:P Little Knight",
    type: "monster",
    subType: "【连接怪兽/效果】",
    attribute: "DARK",
    race: "战士族",
    level: 2,
    atk: 1600,
    def: "-",
    desc: "效果怪兽2只\n①：这张卡用融合·同调·超量·连接怪兽的任意种作为素材连接召唤成功的场合，以对方的场上·墓地1张卡为对象才能发动。那张卡除外。",
    imageUrl: "https://cdn.233.momobako.com/ygopro/pics/29301450.jpg",
    source: "LOCAL_DB",
    rarity: "UR",
    banlistInfo: { masterDuel: 'Semi-Limited', ocg: 'Semi-Limited', tcg: 'Unlimited' }
  },
  {
    id: 84144413,
    name: "天霆号 阿宙斯",
    jpName: "天霆號アーゼウス",
    enName: "Divine Arsenal AA-ZEUS - Sky Thunder",
    type: "monster",
    subType: "【超量怪兽/效果】",
    attribute: "LIGHT",
    race: "机械族",
    level: 12,
    atk: 3000,
    def: 3000,
    desc: "12星怪兽×2\n①：取除这张卡的2个超量素材才能发动。这张卡以外的场上的卡全部送去墓地。",
    imageUrl: "https://cdn.233.momobako.com/ygopro/pics/84144413.jpg",
    source: "LOCAL_DB",
    rarity: "UR",
    banlistInfo: { masterDuel: 'Limited', ocg: 'Limited', tcg: 'Unlimited' }
  },
  {
    id: 83764718,
    name: "墓穴的指名者",
    jpName: "墓穴の指名者",
    enName: "Called by the Grave",
    type: "spell",
    subType: "【速攻魔法】",
    desc: "①：以对方墓地1只怪兽为对象才能发动。那只怪兽除外。",
    imageUrl: "https://cdn.233.momobako.com/ygopro/pics/83764718.jpg",
    source: "LOCAL_DB",
    rarity: "UR",
    banlistInfo: { masterDuel: 'Semi-Limited', ocg: 'Forbidden', tcg: 'Limited' }
  },
  {
    id: 89631139,
    name: "青眼白龙",
    jpName: "青眼の白龍",
    enName: "Blue-Eyes White Dragon",
    type: "monster",
    subType: "【通常怪兽】",
    attribute: "LIGHT",
    race: "龙族",
    level: 8,
    atk: 3000,
    def: 2500,
    desc: "以高攻击力著称的传说之龙。",
    imageUrl: "https://cdn.233.momobako.com/ygopro/pics/89631139.jpg",
    source: "LOCAL_DB",
    rarity: "UR",
    banlistInfo: { masterDuel: 'Unlimited', ocg: 'Unlimited', tcg: 'Unlimited' }
  }
];
